# Generated by Django 2.2.28 on 2024-03-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_advisor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='timeCloses',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='timeOpens',
            field=models.TimeField(null=True),
        ),
    ]
