# Generated by Django 2.2.28 on 2024-03-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_advisor', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='isManager',
            field=models.BooleanField(default=False),
        ),
    ]
