# Generated by Django 2.2.28 on 2024-03-07 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_advisor', '0003_auto_20240307_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='manager',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='food_advisor.UserProfile'),
        ),
    ]
