# Generated by Django 2.2.28 on 2024-03-07 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_advisor', '0004_auto_20240307_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food_advisor.Restaurant'),
        ),
        migrations.AlterField(
            model_name='review',
            name='replyContent',
            field=models.CharField(default='', max_length=128),
        ),
    ]
