# Generated by Django 4.2.11 on 2024-03-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_advisor', '0005_restaurant_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuisineType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='cuisineType',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cuisineTypes',
            field=models.ManyToManyField(blank=True, to='food_advisor.cuisinetype'),
        ),
    ]
