# Generated by Django 4.2.11 on 2024-03-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_advisor', '0006_cuisinetype_remove_restaurant_cuisinetype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
