# Generated by Django 4.2.11 on 2024-03-20 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_advisor', '0011_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='starRating',
            field=models.IntegerField(choices=[(1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')], default=0),
        ),
    ]
